download_github_file_task:
  description: >
    Baixe um único arquivo de código diretamente a partir de um link RAW do GitHub ({url}) 
    e salve-o no caminho local especificado ({output_path}).
  expected_output: >
    O arquivo deve ser salvo em {output_path}, pronto para análise.
  agent: github_file_downloader

clone_repo_task:
  description: >
    Clonar o repositório GitHub localizado em {repo_url} para o diretório {clone_dir}, 
    usando a branch {branch}.
  expected_output: >
    O repositório deve ser clonado com sucesso no {clone_dir}.
  agent: repo_cloner

list_files_task:
  description: >
    Liste os ficheiros de código dentro do diretório {clone_dir}, usando apenas leitura direta do sistema de arquivos real.
    **Não crie, invente ou supoe nomes de ficheiros. Não utilize inteligência artificial para adivinhar arquivos.**
  expected_output: >
    Arquivo list_of_files.txt contendo apenas caminhos reais e existentes de ficheiros no diretório {clone_dir}.
  agent: file_lister

read_file_contents_task:
  description: >
    Abrir o ficheiro list_of_files.txt no diretório atual e, para cada caminho listado, abrir e ler seu conteúdo completo.
    Interpretar estrutura e lógica do código com base nesses ficheiros reais.
  expected_output: >
    Representação lógica detalhada dos ficheiros, incluindo funções, classes e estrutura. Nenhum conteúdo fora dessa lista deve ser considerado.
  agent: file_content_reader

extract_insights_task:
  description: >
    A partir do código analisado e lido diretamente dos ficheiros (conforme list_of_files.txt), 
    extraia todas as funções, classes, métodos ou blocos lógicos principais.
    NÃO assuma a existência de nenhum componente que não esteja claramente presente nos ficheiros.
  expected_output: >
    Uma lista de componentes principais (funções, classes, etc.) que estão claramente presentes no conteúdo lido dos ficheiros.
    Para cada item, forneça uma explicação curta sobre sua finalidade e como se relaciona com os demais componentes do código.
    ⚠️ Atenção: Não inclua absolutamente nada que não esteja presente literalmente no código lido.
  agent: code_insight_agent

generate_doc_task:
  description: >
    Escreva a documentação técnica completa do código com base nos insights extraídos diretamente do conteúdo real dos ficheiros lidos.
    Explique a estrutura, funcionamento, dependências e uso geral, com foco em clareza e fidelidade ao código-fonte.
  expected_output: >
    Um documento técnico detalhado e bem estruturado, pronto para ser incluído no repositório do projeto.
    Toda a explicação deve estar estritamente alinhada ao conteúdo real dos ficheiros lidos.
  agent: doc_writer

markdown_format_task:
  description: >
    Formate a documentação gerada usando sintaxe Markdown. Aplique cabeçalhos, listas, blocos de código 
    e organização hierárquica, garantindo clareza e legibilidade da apresentação final.

    **IMPORTANTE:** A documentação final em Markdown deve refletir apenas o código real presente no diretório {clone_dir} 
    e listado em list_of_files.txt, mesmo que haja apenas um arquivo. Nenhum conteúdo inventado deve ser documentado.
  expected_output: >
    A documentação convertida para Markdown, formatada com estilo limpo, estruturado e pronta para publicação.
  agent: markdown_formatter

