download_github_file_task:
  description: >
    Baixe um único arquivo de código diretamente a partir de um link RAW do GitHub ({url}) 
    e salve-o no caminho local especificado ({output_path}).
  expected_output: >
    O arquivo deve ser salvo em {output_path}, pronto para análise.
  agent: github_file_downloader

clone_repo_task:
  description: >
    Clonar o repositório GitHub localizado em {repo_url} para o diretório {clone_dir}, 
    usando a branch {branch}.
  expected_output: >
    O repositório deve ser clonado com sucesso no {clone_dir}.
  agent: repo_cloner

list_files_task:
  description: >
    Liste os ficheiros de código dentro do diretório {clone_dir}, sem inventar ficheiros.
    Use apenas o sistema de arquivos real. Não infira ficheiros. Não use inteligência artificial para supor nomes de ficheiros.
  expected_output: >
    Lista precisa de caminhos REAIS de ficheiros que existem no diretório {clone_dir}.
  agent: file_lister

read_file_task:
  description: >
    Leia e compreenda cada arquivo da lista gerada que se encontre em {clone_dir}, incluindo estrutura, funções e classes.
  expected_output: >
    Descrição resumida de cada ficheiro analisado, pronto para atualização da documentação inline.
  agent: file_reader

update_inline_docs_task:
  description: >
    Atualize ou escreva docstrings e comentários inline nos ficheiros de código lidos com base na sua lógica.
    Utilize estilo Google ou NumPy.
  expected_output: >
    Código-fonte modificado com docstrings apropriadas e bem estruturadas.
  agent: inline_doc_updater

extract_insights_task:
  description: >
    Extraia as principais estruturas (funções, classes) e relacione-as com a documentação inline já atualizada.
  expected_output: >
    Lista explicativa dos principais componentes do projeto.
  agent: code_insight_agent

generate_doc_task:
  description: >
    Com base nos dados coletados e documentação inline, escreva um documento técnico completo e estruturado.
  expected_output: >
    Documento técnico explicando a estrutura, funcionamento e uso do projeto.
  agent: doc_writer

markdown_format_task:
  description: >
    Formate o conteúdo da documentação técnica em Markdown com estrutura clara e organizada.
  expected_output: >
    Documento em Markdown pronto para publicação.
  agent: markdown_formatter
