download_github_file_task:
  description: >
    Baixe um único arquivo de código diretamente a partir de um link RAW do GitHub ({url}) 
    e salve-o no caminho local especificado ({output_path}) para análise posterior.
  expected_output: >
    O arquivo deve ser baixado com sucesso e salvo em {output_path}, pronto para leitura e análise.
  agent: github_file_downloader

clone_repo_task:
  description: >
    Clonar o repositório GitHub localizado em {repo_url} e salvá-lo localmente no diretório {clone_dir}.
    A operação deve garantir que todo o conteúdo relevante do repositório esteja disponível para análise.
  expected_output: >
    O repositório é clonado corretamente no caminho {clone_dir}, com todos os arquivos acessíveis.
  agent: repo_cloner

read_file_task:
  description: >
    Analise o conteúdo de um arquivo de código salvo em {output_path}. 
    Gere um resumo textual que descreva sua funcionalidade, estrutura lógica, 
    e observações relevantes sobre seu comportamento.
  expected_output: >
    Um resumo descritivo, objetivo e compreensível da lógica do arquivo localizado em {output_path}.
  agent: file_reader

read_directory_task:
  description: >
    Varra todos os arquivos de código no diretório clonado em {clone_dir}, ignorando pastas irrelevantes 
    como `.git` e arquivos que não contenham código-fonte. Analise cada arquivo e sintetize os 
    propósitos principais dos componentes do projeto.
  expected_output: >
    Um resumo técnico da estrutura geral do projeto contido em {clone_dir}, com destaques das principais partes do código.
  agent: directory_reader

extract_insights_task:
  description: >
    A partir do código analisado, extraia todas as funções, classes, métodos ou blocos lógicos principais.
    Para cada item, forneça uma explicação curta sobre sua finalidade e como se relaciona com os demais.
  expected_output: >
    Uma lista de componentes principais (funções, classes, etc.), acompanhada de explicações sucintas 
    sobre seu papel no código.
  agent: code_insight_agent

generate_doc_task:
  description: >
    Escreva a documentação técnica completa do código com base no resumo e nos insights extraídos.
    Explique a estrutura, funcionamento, dependências e uso geral, visando facilitar a manutenção 
    e compreensão por outros desenvolvedores.
  expected_output: >
    Um documento técnico detalhado e bem estruturado, pronto para ser incluído no repositório do projeto.
  agent: doc_writer

markdown_format_task:
  description: >
    Formate a documentação gerada usando sintaxe Markdown. Aplique cabeçalhos, listas, blocos de código 
    e organização hierárquica, garantindo clareza e legibilidade da apresentação final.
  expected_output: >
    A documentação convertida para Markdown, formatada com estilo limpo, estruturado e pronta para publicação.
  agent: markdown_formatter
