download_github_file_task:
  description: >
    Download a single code file directly from the GitHub RAW link.
  expected_output: >
    The file saved at {output_path}.
  agent: github_file_downloader

clone_repo_task:
  description: >
    Clone the GitHub repository to the local directory.
  expected_output: >
    The repository cloned into the {clone_dir} directory.
  agent: repo_cloner

list_files_task:
  description: >
    List files from the cloned repository.
  expected_output: >
    Returns the listed files in {output_file}.
  agent: file_lister

code_exporter_task:
  description: >
    Read the file {list_file_path}, which contains paths to code files (one per line).
    For each listed path:
      - Read the content of the corresponding file.
      - Add a comment header with the file name, in the format "# File: path/file.py".
    Combine everything in sequence and save it to {final_result}.
  expected_output: >
    The file {final_result}, containing the concatenation of all listed files,
    with clear separation using valid comments (e.g., "# File: ...").
    No content should be invented or modified — only faithful reading and writing of actual files.
  agent: code_exporter

cleaner_task:
  description: >
    Process the {final_result} file containing multiple code blocks, merging them into a single file {final_text},
    removing emojis, and adjusting the extension according to the detected language.
  expected_output: >
    A consolidated single file with clean code, ready for analysis.
  agent: cleaner
