# ---------------------------------------------------
# Tasks for clone_repo method (multiple files)
# ---------------------------------------------------

read_code_task:
  description: >
    Read the content of the file specified by {final_text}, which is a `.txt` containing
    all files from a previously cloned GitHub repository, combined into a single file.
  expected_output: >
    The raw content of the file {final_text}, exactly as it is, including
    all "# FILE: path/name.py" markers.
  agent: code_reader

extract_insights_task:
  description: >
    From the read content, analyze each section (divided by "# FILE: path/name.py" markers)
    and identify functions, classes, and main structures, explaining their role and
    relationship with other components. The agent must base its analysis strictly on
    the provided content without creating or assuming additional files or sections.
  expected_output: >
    Bullet-point list organized by file, containing functions, classes,
    and main structures, with descriptions of their role in the project.
    Do not mention files that are not present in the content.
  agent: code_insight_agent

generate_summary_task:
  description: >
    Using the extracted insights, generate a general summary explaining the functionality
    of the cloned repository as a whole, highlighting how different files and components
    work together.
  expected_output: >
    A clear and concise summary of the purpose and overall functioning of the system.
  agent: doc_writer

generate_doc_task:
  description: >
    Based on the general summary and insights, write complete technical documentation,
    describing each file, its main classes and functions, and how they relate to each
    other in the cloned repository.
  expected_output: >
    Detailed technical documentation, structured by file, ready for developer use.
  agent: doc_writer

markdown_format_task:
  description: >
    Format the technical documentation in Markdown, creating separate sections by file
    and including a general introduction about the cloned repository.
  expected_output: >
    Technical documentation in Markdown, well organized, with titles, lists,
    and code blocks.
  agent: markdown_formatter

# ---------------------------------------------------
# Tasks for raw_link method (single file) - translated
# ---------------------------------------------------

read_code_task_raw_link:
  description: >
    Read the content of the file specified by {output_path} using the file reading tool
    and generate a general summary explaining the overall functionality of the code.
  expected_output: >
    A textual summary explaining the general functionality of the file, including
    its main functions and classes and how they interact.
  agent: raw_code_reader

extract_insights_task_raw_link:
  description: >
    Based on the general summary of the file, analyze the code and identify the main
    functions, classes, and structures, describing their role and how they relate to
    each other.
  expected_output: >
    Bullet-point list containing function, class, and structure names,
    accompanied by a brief explanation of their functionality and interactions.
  agent: code_insight_agent

generate_doc_task_raw_link:
  description: >
    Using the general summary and extracted insights, write complete technical documentation
    for the file. Describe its purpose, main classes and functions, and how these elements
    compose the code's functionality.
  expected_output: >
    Detailed technical documentation of the file, with clear and technical explanations.
  agent: doc_writer

markdown_format_task_raw_link:
  description: >
    Format the technical documentation in Markdown, organizing the content into clear sections.
    Use titles, lists, and code blocks to facilitate reading and navigation.
  expected_output: >
    Technical documentation formatted in Markdown in a readable and organized manner.
  agent: markdown_formatter
