read_code_task:
  description: >
    Leia e analise todos os arquivos Python no diretório "./codigo".
    Forneça um resumo textual conciso explicando a funcionalidade geral do código de cada ficheiro,
    destacando seu propósito principal e estrutura geral.
  expected_output: >
    Um resumo em linguagem natural para programadores, explicando o que cada ficheiro faz de forma clara.
  agent: code_reader

extract_insights_task:
  description: >
    A partir do resumo gerado, identifique e liste todas as funções, classes e estruturas principais.
    Para cada item, forneça uma breve explicação do seu papel dentro do sistema e como ele se relaciona com os demais.
  expected_output: >
    Lista em bullet points com funções, classes e seus papéis explicados.
  agent: code_insight_agent

generate_doc_task:
  description: >
    Com base nos resumos e insights, redija uma documentação técnica clara e completa.
    A documentação deve explicar como o sistema funciona e como pode ser usado.
  expected_output: >
    Documento técnico explicando estrutura, uso e dependências do código Python analisado.
  agent: doc_writer

markdown_format_task:
  description: >
    Formate a documentação técnica gerada anteriormente usando Markdown.
    Use títulos, listas, blocos de código e boa estrutura visual.
  expected_output: >
    Documentação bem formatada em Markdown, pronta para uso em repositórios.
  agent: markdown_formatter
